# Generated by Django 2.0.13 on 2019-03-26 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_dieta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dieta', to='paciente.Paciente'),
        ),
    ]
