# Generated by Django 2.0.13 on 2019-03-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20190326_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dieta_paciente', to='paciente.Paciente'),
        ),
    ]
