# Generated by Django 2.0.13 on 2019-03-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20190326_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='paciente',
        ),
        migrations.AddField(
            model_name='dieta',
            name='paciente',
            field=models.ManyToManyField(to='paciente.Paciente'),
        ),
    ]
