# Generated by Django 2.0.13 on 2019-03-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20190326_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='paciente',
            field=models.ManyToManyField(related_name='dieta', to='paciente.Paciente'),
        ),
    ]
