# Generated by Django 2.0.13 on 2019-04-02 22:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_auto_20190327_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('1', 'consulta'), ('2', 'retorno')], max_length=20)),
                ('local', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('crn', models.CharField(max_length=20)),
                ('especialidades', models.ManyToManyField(related_name='nutricionistas', to='paciente.Especialidade')),
            ],
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='idade',
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('1', 'masculino'), ('2', 'feminino')], max_length=20),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='paciente.Consulta')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='dieta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Dieta'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nutricionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Nutricionista'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
    ]
