# Generated by Django 2.0.13 on 2019-04-03 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_auto_20190402_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='consulta',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='avaliacao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Avaliacao'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='dieta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Dieta'),
        ),
    ]
